export type Property = {
  id: number;
  title: string;
  description: string;
  propertyType: 'rent' | 'buy' | 'service-apartment' | 'rent-to-own';
  category: string;
  address: string;
  location: string;
  city: string;
  state: string;
  postcode?: string;

  // Images
  images: string[];

  // Core specs
  bedrooms: number;
  bathrooms: number;
  floorSize?: number;

  // Amenities
  furnished?: boolean;
  parking?: boolean;
  garden?: boolean;
  pool?: boolean;
  gym?: boolean;

  // Pricing & financial
  price: number;             // sale price or total price
  monthlyPrice?: number;     // monthly rent or rent-to-own payment
  deposit?: number;
  fees?: number;
  currency?: string;

  // Advanced search / listing info
  featured: boolean;
  verified: boolean;
  isNew: boolean;
  availableFrom?: string;               // ISO date string for availability
  status?: 'available' | 'sold' | 'let-agreed';
  keywords?: string[];                  // for advanced keyword search
  latitude?: number;                    // for radius/map searches
  longitude?: number;                   // for radius/map searches

  // Agent info
  agentName?: string;
  agentContact?: string;
  agency?: string;

  // Nearby & transport
  schoolsNearby?: string[];
  transportLinks?: string[];
};


export const allProperties: Property[] = [
  // ===================== RENT (10) =====================
  {
    id: 1,
    title: '3 Bedroom Flat, Lokogoma, Abuja',
    description: 'Spacious 3-bedroom flat with balcony and parking.',
    propertyType: 'rent',
    category: 'residential-properties-to-rent',
    address: 'Plot 12, Lokogoma District',
    location: 'Near Wuse Market',
    city: 'Abuja',
    state: 'Abuja FCT',
    postcode: '900271',
    images: ['/assets/marketplace-assets/home1.png', '/assets/marketplace-assets/home1-2.png'],
    bedrooms: 3,
    bathrooms: 4,
    floorSize: 1800,
    furnished: true,
    parking: true,
    garden: true,
    pool: false,
    gym: false,
    price: 2500000,
    monthlyPrice: 250000,
    deposit: 500000,
    fees: 20000,
    currency: 'NGN',
    featured: true,
    verified: true,
    isNew: false,
    availableFrom: '2025-12-01',
    status: 'available',
    agentName: 'John Doe',
    agentContact: '+2348012345678',
    agency: 'Prime Homes Realty',
    schoolsNearby: ['Lokogoma Primary', 'Unity College'],
    transportLinks: ['Bus stop 200m'],
    keywords: ['balcony', 'parking', 'spacious', 'family'],
    latitude: 9.0723,
    longitude: 7.4910,
  },
  {
    id: 2,
    title: 'Student Apartment, Victoria Island, Lagos',
    description: 'Ideal for students, fully furnished, close to transport.',
    propertyType: 'rent',
    category: 'student-properties-to-rent',
    address: '12 Adeola Odeku Street',
    location: 'Victoria Island',
    city: 'Lagos',
    state: 'Lagos',
    postcode: '101241',
    images: ['/assets/marketplace-assets/home2.png', '/assets/marketplace-assets/home2-2.png'],
    bedrooms: 2,
    bathrooms: 2,
    floorSize: 900,
    furnished: true,
    parking: false,
    garden: false,
    pool: true,
    gym: true,
    price: 1500000,
    monthlyPrice: 150000,
    deposit: 300000,
    fees: 15000,
    currency: 'NGN',
    featured: false,
    verified: true,
    isNew: true,
    availableFrom: '2025-12-10',
    status: 'available',
    agentName: 'Jane Smith',
    agentContact: '+2348023456789',
    agency: 'Island Properties',
    schoolsNearby: ['Lagos Business School'],
    transportLinks: ['Bus stop 100m', 'Ferry 500m'],
    keywords: ['student', 'furnished', 'central', 'convenient'],
    latitude: 6.4281,
    longitude: 3.4217,
  },
  {
    id: 3,
    title: 'Corporate Flat, Lekki Phase 1, Lagos',
    description: 'Perfect for executives with modern amenities.',
    propertyType: 'rent',
    category: 'corporate-properties-to-rent',
    address: 'Plot 45, Lekki Phase 1',
    location: 'Lekki Toll Gate',
    city: 'Lagos',
    state: 'Lagos',
    postcode: '101233',
    images: ['/assets/marketplace-assets/home3.png', '/assets/marketplace-assets/home3-2.png'],
    bedrooms: 3,
    bathrooms: 4,
    floorSize: 1400,
    furnished: true,
    parking: true,
    pool: true,
    gym: true,
    price: 4000000,
    monthlyPrice: 400000,
    deposit: 500000,
    fees: 20000,
    currency: 'NGN',
    featured: true,
    verified: true,
    isNew: true,
    availableFrom: '2025-12-05',
    status: 'available',
    agentName: 'Michael Obi',
    agentContact: '+2348035671234',
    agency: 'Lekki Realty',
    schoolsNearby: ['Lekki British School'],
    transportLinks: ['Bus stop 150m', 'Lekki-Epe Expressway 500m'],
    keywords: ['executive', 'modern', 'pool', 'gym', 'corporate'],
    latitude: 6.4390,
    longitude: 3.5200,
  },
  // ===================== BUY (10) =====================
  {
  id: 11,
  title: '5 Bedroom Mansion, Banana Island, Lagos',
  description: 'Exquisite mansion for high-end buyers with private pool and garden.',
  propertyType: 'buy',
  category: 'residential-properties-for-sale',
  address: 'Plot 21, Banana Island',
  location: 'Luxury waterfront estate',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101221',
  images: ['/assets/marketplace-assets/home11.png'],
  bedrooms: 5,
  bathrooms: 6,
  floorSize: 4000,
  furnished: true,
  parking: true,
  garden: true,
  pool: true,
  gym: true,
  price: 250000000,
  currency: 'NGN',
  featured: true,
  verified: true,
  isNew: false,
  status: 'available',
  agentName: 'Victor Martins',
  agentContact: '+2348029988776',
  agency: 'Luxury Lagos Estates',
  schoolsNearby: ['Lagos International School'],
  transportLinks: ['Bus stop 200m', 'Airport 15 min'],
  keywords: ['mansion', 'luxury', 'private pool', 'garden', 'waterfront'],
  latitude: 6.4350,
  longitude: 3.3792,
},
{
  id: 12,
  title: '3 Bedroom Terrace, Wuse 2, Abuja',
  description: 'Modern terrace house in a gated community.',
  propertyType: 'buy',
  category: 'residential-properties-for-sale',
  address: 'Plot 33, Wuse 2',
  location: 'Quiet residential neighborhood',
  city: 'Abuja',
  state: 'Abuja FCT',
  postcode: '900230',
  images: ['/assets/marketplace-assets/home12.png'],
  bedrooms: 3,
  bathrooms: 3,
  floorSize: 1800,
  furnished: true,
  parking: true,
  garden: true,
  pool: false,
  gym: true,
  price: 50000000,
  currency: 'NGN',
  featured: false,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Chuka Nwosu',
  agentContact: '+2348034455667',
  agency: 'Abuja Realty',
  schoolsNearby: ['Capital International School'],
  transportLinks: ['Bus stop 150m'],
  keywords: ['terrace', 'gated community', 'modern', 'family-friendly'],
  latitude: 9.0800,
  longitude: 7.4950,
},
{
  id: 13,
  title: '4 Bedroom Semi-Detached, Lekki, Lagos',
  description: 'Family-friendly semi-detached house near highways.',
  propertyType: 'buy',
  category: 'residential-properties-for-sale',
  address: 'Plot 10, Lekki Phase 1',
  location: 'Close to major highways',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101222',
  images: ['/assets/marketplace-assets/home13.png'],
  bedrooms: 4,
  bathrooms: 4,
  floorSize: 2200,
  furnished: true,
  parking: true,
  garden: true,
  pool: true,
  gym: true,
  price: 85000000,
  currency: 'NGN',
  featured: true,
  verified: true,
  isNew: false,
  status: 'available',
  agentName: 'Olufemi Adeyemi',
  agentContact: '+2348023344556',
  agency: 'Lekki Properties',
  schoolsNearby: ['Lekki British School'],
  transportLinks: ['Bus stop 100m', 'Lekki-Epe Expressway 500m'],
  keywords: ['semi-detached', 'family', 'highways', 'modern', 'pool'],
  latitude: 6.4415,
  longitude: 3.5240,
},
{
  id: 14,
  title: '2 Bedroom Bungalow, Jos, Plateau',
  description: 'Cozy bungalow perfect for small families.',
  propertyType: 'buy',
  category: 'residential-properties-for-sale',
  address: 'Plot 14, Jos North',
  location: 'Peaceful neighborhood',
  city: 'Jos',
  state: 'Plateau',
  postcode: '930221',
  images: ['/assets/marketplace-assets/home14.png'],
  bedrooms: 2,
  bathrooms: 2,
  floorSize: 1000,
  furnished: true,
  parking: true,
  garden: true,
  pool: false,
  gym: false,
  price: 18000000,
  currency: 'NGN',
  featured: false,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Bala Yakubu',
  agentContact: '+2348021123345',
  agency: 'Jos Realty',
  schoolsNearby: ['Plateau International School'],
  transportLinks: ['Bus stop 100m'],
  keywords: ['bungalow', 'cozy', 'small family', 'peaceful'],
  latitude: 9.8965,
  longitude: 8.8583,
},
{
  id: 15,
  title: '3 Bedroom Flat, Oniru, Lagos',
  description: 'Modern flat with parking and security.',
  propertyType: 'buy',
  category: 'residential-properties-for-sale',
  address: 'Plot 5, Oniru',
  location: 'Near shopping and entertainment',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101231',
  images: ['/assets/marketplace-assets/home15.png'],
  bedrooms: 3,
  bathrooms: 3,
  floorSize: 1600,
  furnished: true,
  parking: true,
  garden: false,
  pool: true,
  gym: false,
  price: 45000000,
  currency: 'NGN',
  featured: true,
  verified: true,
  isNew: false,
  status: 'available',
  agentName: 'Adewale Ogun',
  agentContact: '+2348022233445',
  agency: 'Lagos Real Estate',
  schoolsNearby: ['Victoria International School'],
  transportLinks: ['Bus stop 50m'],
  keywords: ['flat', 'modern', 'parking', 'security', 'convenient'],
  latitude: 6.4260,
  longitude: 3.4280,
},
{
  id: 16,
  title: 'Commercial Office Space, Victoria Island, Lagos',
  description: 'Prime commercial space for business setup.',
  propertyType: 'buy',
  category: 'commercial-properties-for-sale',
  address: 'Plot 20, Victoria Island',
  location: 'Central Business District',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101245',
  images: ['/assets/marketplace-assets/home16.png'],
  bedrooms: 0,
  bathrooms: 2,
  floorSize: 2000,
  furnished: true,
  parking: true,
  garden: false,
  pool: false,
  gym: false,
  price: 95000000,
  currency: 'NGN',
  featured: true,
  verified: true,
  isNew: false,
  status: 'available',
  agentName: 'Sola Ajayi',
  agentContact: '+2348034456778',
  agency: 'Victoria Offices',
  schoolsNearby: [],
  transportLinks: ['Bus stop 100m', 'Ferry 500m'],
  keywords: ['commercial', 'office', 'CBD', 'prime location'],
  latitude: 6.4275,
  longitude: 3.4210,
},
{
  id: 17,
  title: 'Commercial Retail Space, Lekki, Lagos',
  description: 'Retail space perfect for shops or showrooms.',
  propertyType: 'buy',
  category: 'commercial-properties-for-sale',
  address: 'Plot 7, Lekki Phase 1',
  location: 'Near Toll Gate',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101223',
  images: ['/assets/marketplace-assets/home17.png'],
  bedrooms: 0,
  bathrooms: 2,
  floorSize: 1500,
  furnished: false,
  parking: true,
  garden: false,
  pool: false,
  gym: false,
  price: 65000000,
  currency: 'NGN',
  featured: false,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Tosin Bello',
  agentContact: '+2348023344557',
  agency: 'Lekki Commercials',
  schoolsNearby: [],
  transportLinks: ['Bus stop 50m'],
  keywords: ['commercial', 'retail', 'showroom', 'prime location'],
  latitude: 6.4400,
  longitude: 3.5205,
},
{
  id: 18,
  title: 'Student Housing, Jabi, Abuja',
  description: 'Affordable housing for students, fully furnished.',
  propertyType: 'buy',
  category: 'student-properties-for-sale',
  address: 'Plot 12, Jabi',
  location: 'Close to universities',
  city: 'Abuja',
  state: 'Abuja FCT',
  postcode: '900212',
  images: ['/assets/marketplace-assets/home18.png'],
  bedrooms: 2,
  bathrooms: 1,
  floorSize: 800,
  furnished: true,
  parking: false,
  garden: false,
  pool: false,
  gym: false,
  price: 12000000,
  currency: 'NGN',
  featured: false,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Hassan Musa',
  agentContact: '+2348032233445',
  agency: 'Jabi Estates',
  schoolsNearby: ['University of Abuja'],
  transportLinks: ['Bus stop 50m'],
  keywords: ['student', 'affordable', 'furnished', 'near universities'],
  latitude: 9.0810,
  longitude: 7.4340,
},
{
  id: 19,
  title: 'Corporate Apartment, Victoria Island, Lagos',
  description: 'Ideal for professionals, close to office districts.',
  propertyType: 'buy',
  category: 'corporate-properties-for-sale',
  address: 'Plot 15, Victoria Island',
  location: 'Business District',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101242',
  images: ['/assets/marketplace-assets/home19.png'],
  bedrooms: 3,
  bathrooms: 3,
  floorSize: 1400,
  furnished: true,
  parking: true,
  garden: false,
  pool: true,
  gym: true,
  price: 55000000,
  currency: 'NGN',
  featured: true,
  verified: true,
  isNew: false,
  status: 'available',
  agentName: 'Femi Ade',
  agentContact: '+2348023345568',
  agency: 'Victoria Corporate Homes',
  schoolsNearby: [],
  transportLinks: ['Bus stop 50m'],
  keywords: ['corporate', 'executive', 'professionals', 'pool', 'central'],
  latitude: 6.4270,
  longitude: 3.4235,
},
{
  id: 20,
  title: 'Corporate Apartment, Lekki Phase 1, Lagos',
  description: 'Modern apartment ideal for corporate tenants.',
  propertyType: 'buy',
  category: 'corporate-properties-for-sale',
  address: 'Plot 18, Lekki Phase 1',
  location: 'Near Lekki Toll Gate',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101225',
  images: ['/assets/marketplace-assets/home20.png'],
  bedrooms: 3,
  bathrooms: 3,
  floorSize: 1500,
  furnished: true,
  parking: true,
  garden: false,
  pool: true,
  gym: true,
  price: 60000000,
  currency: 'NGN',
  featured: true,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Adewale Johnson',
  agentContact: '+2348023345569',
  agency: 'Lekki Corporate Realty',
  schoolsNearby: [],
  transportLinks: ['Bus stop 50m', 'Highway 200m'],
  keywords: ['corporate', 'modern', 'executive', 'pool', 'gym'],
  latitude: 6.4390,
  longitude: 3.5200,
},


  // ===================== SERVICE APARTMENTS (10) =====================

  {
  id: 21,
  title: 'Luxury City Center Studio, Ikeja, Lagos',
  description: 'Fully furnished studio in the heart of Lagos, ideal for corporate stays.',
  propertyType: 'service-apartment',
  category: 'short-term',
  address: '12 Allen Avenue, Ikeja',
  location: 'Ikeja City Mall Area',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '100001',
  images: ['/assets/marketplace-assets/service21.png'],
  bedrooms: 1,
  bathrooms: 1,
  floorSize: 500,
  furnished: true,
  parking: true,
  garden: false,
  pool: false,
  gym: true,
  price: 50000,
  currency: 'NGN',
  featured: true,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Tunde Olawale',
  agentContact: '+2348012345678',
  agency: 'Ikeja Serviced Homes',
  schoolsNearby: [],
  transportLinks: ['Bus stop 100m', 'Main Road 50m'],
  keywords: ['studio', 'luxury', 'corporate', 'furnished', 'central'],
  latitude: 6.6018,
  longitude: 3.3515,
},
{
  id: 22,
  title: 'Executive 2-Bedroom Apartment, Victoria Island, Lagos',
  description: 'Spacious apartment with modern amenities, perfect for business travelers.',
  propertyType: 'service-apartment',
  category: 'corporate',
  address: '24 Ozumba Mbadiwe Avenue, Victoria Island',
  location: 'Near Landmark Centre',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101241',
  images: ['/assets/marketplace-assets/service22.png'],
  bedrooms: 2,
  bathrooms: 2,
  floorSize: 1200,
  furnished: true,
  parking: true,
  garden: false,
  pool: true,
  gym: true,
  price: 120000,
  currency: 'NGN',
  featured: false,
  verified: true,
  isNew: false,
  status: 'available',
  agentName: 'Chika Nwosu',
  agentContact: '+2348022233445',
  agency: 'VI Luxury Stays',
  schoolsNearby: [],
  transportLinks: ['Bus stop 50m', 'Highway 100m'],
  keywords: ['apartment', 'executive', 'corporate', 'luxury', 'pool'],
  latitude: 6.4280,
  longitude: 3.4215,
},
{
  id: 23,
  title: 'Luxury Penthouse Suite, Lekki, Lagos',
  description: 'High-end penthouse with city views and premium furnishings.',
  propertyType: 'service-apartment',
  category: 'luxury',
  address: '45 Admiralty Way, Lekki Phase 1',
  location: 'Near Lekki Toll Gate',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '105102',
  images: ['/assets/marketplace-assets/service23.png'],
  bedrooms: 3,
  bathrooms: 3,
  floorSize: 1800,
  furnished: true,
  parking: true,
  garden: true,
  pool: true,
  gym: true,
  price: 250000,
  currency: 'NGN',
  featured: true,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Akin Bello',
  agentContact: '+2348033344556',
  agency: 'Lekki Luxury Suites',
  schoolsNearby: [],
  transportLinks: ['Bus stop 80m', 'Expressway 200m'],
  keywords: ['penthouse', 'luxury', 'city view', 'pool', 'furnished'],
  latitude: 6.4420,
  longitude: 3.5280,
},
{
  id: 24,
  title: 'Cozy 1-Bedroom Flat, Ikoyi, Lagos',
  description: 'Compact, fully serviced apartment ideal for short stays.',
  propertyType: 'service-apartment',
  category: 'short-term',
  address: '18 Bourdillon Road, Ikoyi',
  location: 'Near Ikoyi Club',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101233',
  images: ['/assets/marketplace-assets/service24.png'],
  bedrooms: 1,
  bathrooms: 1,
  floorSize: 550,
  furnished: true,
  parking: true,
  garden: false,
  pool: false,
  gym: true,
  price: 45000,
  currency: 'NGN',
  featured: false,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Olufunke Adeyemi',
  agentContact: '+2348056677889',
  agency: 'Ikoyi Serviced Apartments',
  schoolsNearby: [],
  transportLinks: ['Bus stop 50m', 'Main Road 100m'],
  keywords: ['flat', 'cozy', 'short-term', 'furnished', 'central'],
  latitude: 6.4285,
  longitude: 3.4285,
},
{
  id: 25,
  title: 'Corporate 2-Bedroom Apartment, Yaba, Lagos',
  description: 'Modern apartment with coworking-friendly spaces and facilities.',
  propertyType: 'service-apartment',
  category: 'corporate',
  address: '12 Herbert Macaulay Way, Yaba',
  location: 'Near Yaba Tech',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '100212',
  images: ['/assets/marketplace-assets/service25.png'],
  bedrooms: 2,
  bathrooms: 2,
  floorSize: 1100,
  furnished: true,
  parking: true,
  garden: false,
  pool: false,
  gym: true,
  price: 90000,
  currency: 'NGN',
  featured: false,
  verified: true,
  isNew: false,
  status: 'available',
  agentName: 'Bola Akinlade',
  agentContact: '+2348028899001',
  agency: 'Yaba Corporate Homes',
  schoolsNearby: [],
  transportLinks: ['Bus stop 30m', 'Highway 150m'],
  keywords: ['apartment', 'corporate', 'modern', 'coworking', 'furnished'],
  latitude: 6.5150,
  longitude: 3.3840,
},
{
  id: 26,
  title: 'Luxury Studio with Pool Access, Surulere, Lagos',
  description: 'Stylish studio offering pool access and 24/7 security.',
  propertyType: 'service-apartment',
  category: 'luxury',
  address: '5 Fola Osibo Street, Surulere',
  location: 'Near National Stadium',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101283',
  images: ['/assets/marketplace-assets/service26.png'],
  bedrooms: 1,
  bathrooms: 1,
  floorSize: 600,
  furnished: true,
  parking: true,
  garden: false,
  pool: true,
  gym: true,
  price: 55000,
  currency: 'NGN',
  featured: true,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Kemi Olatunji',
  agentContact: '+2348039988776',
  agency: 'Surulere Luxury Suites',
  schoolsNearby: [],
  transportLinks: ['Bus stop 20m', 'Expressway 100m'],
  keywords: ['studio', 'luxury', 'pool', 'security', 'furnished'],
  latitude: 6.5050,
  longitude: 3.3750,
},
{
  id: 27,
  title: '3-Bedroom Executive Apartment, Lekki Phase 1, Lagos',
  description: 'Spacious apartment with fully equipped kitchen and lounge.',
  propertyType: 'service-apartment',
  category: 'corporate',
  address: '22 Admiralty Way, Lekki Phase 1',
  location: 'Near Chevron Roundabout',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '105102',
  images: ['/assets/marketplace-assets/service27.png'],
  bedrooms: 3,
  bathrooms: 3,
  floorSize: 1700,
  furnished: true,
  parking: true,
  garden: true,
  pool: true,
  gym: true,
  price: 200000,
  currency: 'NGN',
  featured: true,
  verified: true,
  isNew: false,
  status: 'available',
  agentName: 'Emeka Okafor',
  agentContact: '+2348025566778',
  agency: 'Lekki Executive Homes',
  schoolsNearby: [],
  transportLinks: ['Bus stop 50m', 'Highway 150m'],
  keywords: ['apartment', 'executive', 'corporate', 'pool', 'luxury'],
  latitude: 6.4425,
  longitude: 3.5260,
},
{
  id: 28,
  title: 'Modern 1-Bedroom Loft, Victoria Island, Lagos',
  description: 'Loft-style apartment, ideal for short-term luxury stays.',
  propertyType: 'service-apartment',
  category: 'short-term',
  address: '30 Ahmadu Bello Way, Victoria Island',
  location: 'Near Eko Hotel',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101241',
  images: ['/assets/marketplace-assets/service28.png'],
  bedrooms: 1,
  bathrooms: 1,
  floorSize: 650,
  furnished: true,
  parking: true,
  garden: false,
  pool: false,
  gym: true,
  price: 60000,
  currency: 'NGN',
  featured: false,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Funmi Adeoye',
  agentContact: '+2348023341122',
  agency: 'VI Modern Lofts',
  schoolsNearby: [],
  transportLinks: ['Bus stop 40m', 'Main Road 60m'],
  keywords: ['loft', 'modern', 'short-term', 'furnished', 'central'],
  latitude: 6.4280,
  longitude: 3.4215,
},
{
  id: 29,
  title: 'Elegant 2-Bedroom Flat, Ikeja GRA, Lagos',
  description: 'Furnished flat with modern appliances, suited for business trips.',
  propertyType: 'service-apartment',
  category: 'corporate',
  address: '8 GRA Street, Ikeja GRA',
  location: 'Near Ikeja GRA Market',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '100271',
  images: ['/assets/marketplace-assets/service29.png'],
  bedrooms: 2,
  bathrooms: 2,
  floorSize: 1200,
  furnished: true,
  parking: true,
  garden: false,
  pool: true,
  gym: true,
  price: 100000,
  currency: 'NGN',
  featured: false,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Tobi Lawal',
  agentContact: '+2348031123345',
  agency: 'Ikeja Executive Suites',
  schoolsNearby: [],
  transportLinks: ['Bus stop 50m', 'Highway 100m'],
  keywords: ['flat', 'corporate', 'furnished', 'modern', 'pool'],
  latitude: 6.6030,
  longitude: 3.3520,
},
{
  id: 30,
  title: 'Premium 1-Bedroom Apartment, Ikoyi, Lagos',
  description: 'High-quality serviced apartment with concierge and amenities.',
  propertyType: 'service-apartment',
  category: 'luxury',
  address: '12 Kingsway Road, Ikoyi',
  location: 'Near Ikoyi Club',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101233',
  images: ['/assets/marketplace-assets/service30.png'],
  bedrooms: 1,
  bathrooms: 1,
  floorSize: 700,
  furnished: true,
  parking: true,
  garden: false,
  pool: true,
  gym: true,
  price: 70000,
  currency: 'NGN',
  featured: true,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Adeola Fashola',
  agentContact: '+2348024456677',
  agency: 'Ikoyi Premium Suites',
  schoolsNearby: [],
  transportLinks: ['Bus stop 20m', 'Main Road 50m'],
  keywords: ['apartment', 'luxury', 'premium', 'pool', 'furnished'],
  latitude: 6.4285,
  longitude: 3.4290,
},
  // ===================== RENT-TO-OWN (10) =====================
{
  id: 31,
  title: '3-Bedroom Family Home, Lekki Phase 1, Lagos',
  description: 'Spacious family home available for rent-to-own.',
  propertyType: 'rent-to-own',
  category: 'family-home',
  address: '14 Admiralty Way, Lekki Phase 1',
  location: 'Near Chevron Roundabout',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '105102',
  images: ['/assets/marketplace-assets/rent31.png'],
  bedrooms: 3,
  bathrooms: 3,
  floorSize: 1600,
  furnished: true,
  parking: true,
  garden: true,
  pool: true,
  gym: true,
  price: 50000000,
  currency: 'NGN',
  featured: true,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Chuka Nwafor',
  agentContact: '+2348023345560',
  agency: 'Lekki Homes Ltd',
  schoolsNearby: ['Greensprings School', 'Lekki British School'],
  transportLinks: ['Bus stop 50m', 'Highway 200m'],
  keywords: ['family home', '3-bedroom', 'rent-to-own', 'luxury', 'pool'],
  latitude: 6.4420,
  longitude: 3.5300,
},
{
  id: 32,
  title: '4-Bedroom Duplex, Ikoyi, Lagos',
  description: 'Modern duplex with flexible rent-to-own options.',
  propertyType: 'rent-to-own',
  category: 'duplex',
  address: '20 Bourdillon Road, Ikoyi',
  location: 'Near Ikoyi Club',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101233',
  images: ['/assets/marketplace-assets/rent32.png'],
  bedrooms: 4,
  bathrooms: 4,
  floorSize: 2500,
  furnished: true,
  parking: true,
  garden: true,
  pool: true,
  gym: true,
  price: 120000000,
  currency: 'NGN',
  featured: true,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Funke Adeyemi',
  agentContact: '+2348033345566',
  agency: 'Ikoyi Prime Realty',
  schoolsNearby: ['Corona Ikoyi', 'Lagos Preparatory School'],
  transportLinks: ['Bus stop 80m', 'Main Road 100m'],
  keywords: ['duplex', '4-bedroom', 'rent-to-own', 'luxury', 'pool'],
  latitude: 6.4285,
  longitude: 3.4290,
},
{
  id: 33,
  title: '2-Bedroom Apartment, Victoria Island, Lagos',
  description: 'Cozy apartment ideal for small families under rent-to-own scheme.',
  propertyType: 'rent-to-own',
  category: 'apartment',
  address: '12 Ahmadu Bello Way, Victoria Island',
  location: 'Near Eko Hotel',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101241',
  images: ['/assets/marketplace-assets/rent33.png'],
  bedrooms: 2,
  bathrooms: 2,
  floorSize: 900,
  furnished: true,
  parking: true,
  garden: false,
  pool: false,
  gym: true,
  price: 35000000,
  currency: 'NGN',
  featured: false,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Tobi Lawal',
  agentContact: '+2348024456677',
  agency: 'VI Rentals & Realty',
  schoolsNearby: ['Greensprings School', 'Lekki British School'],
  transportLinks: ['Bus stop 40m', 'Highway 50m'],
  keywords: ['apartment', '2-bedroom', 'rent-to-own', 'cozy', 'furnished'],
  latitude: 6.4275,
  longitude: 3.4210,
},
{
  id: 34,
  title: '3-Bedroom Terrace, Lekki Phase 2, Lagos',
  description: 'Beautiful terrace home available for rent-to-own buyers.',
  propertyType: 'rent-to-own',
  category: 'terrace-house',
  address: '5 Chevron Drive, Lekki Phase 2',
  location: 'Near Chevron Roundabout',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '105104',
  images: ['/assets/marketplace-assets/rent34.png'],
  bedrooms: 3,
  bathrooms: 2,
  floorSize: 1400,
  furnished: true,
  parking: true,
  garden: true,
  pool: false,
  gym: true,
  price: 45000000,
  currency: 'NGN',
  featured: false,
  verified: true,
  isNew: false,
  status: 'available',
  agentName: 'Emeka Okafor',
  agentContact: '+2348035566778',
  agency: 'Lekki Rent2Own Homes',
  schoolsNearby: ['Lekki British School'],
  transportLinks: ['Bus stop 50m', 'Highway 150m'],
  keywords: ['terrace', '3-bedroom', 'rent-to-own', 'garden', 'furnished'],
  latitude: 6.4450,
  longitude: 3.5400,
},
{
  id: 35,
  title: '4-Bedroom Detached House, Ikoyi, Lagos',
  description: 'Luxury detached home with rent-to-own option.',
  propertyType: 'rent-to-own',
  category: 'detached-house',
  address: '10 Kingsway Road, Ikoyi',
  location: 'Near Ikoyi Club',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101233',
  images: ['/assets/marketplace-assets/rent35.png'],
  bedrooms: 4,
  bathrooms: 4,
  floorSize: 2600,
  furnished: true,
  parking: true,
  garden: true,
  pool: true,
  gym: true,
  price: 150000000,
  currency: 'NGN',
  featured: true,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Chika Nwosu',
  agentContact: '+2348023345560',
  agency: 'Ikoyi Luxury Estates',
  schoolsNearby: ['Corona Ikoyi'],
  transportLinks: ['Bus stop 60m', 'Main Road 80m'],
  keywords: ['detached', '4-bedroom', 'rent-to-own', 'luxury', 'pool'],
  latitude: 6.4290,
  longitude: 3.4300,
},
{
  id: 36,
  title: '3-Bedroom Semi-Detached House, Lekki, Lagos',
  description: 'Modern semi-detached home available for rent-to-own buyers.',
  propertyType: 'rent-to-own',
  category: 'semi-detached',
  address: '18 Admiralty Way, Lekki Phase 1',
  location: 'Near Lekki Toll Gate',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '105102',
  images: ['/assets/marketplace-assets/rent36.png'],
  bedrooms: 3,
  bathrooms: 3,
  floorSize: 1500,
  furnished: true,
  parking: true,
  garden: true,
  pool: true,
  gym: true,
  price: 60000000,
  currency: 'NGN',
  featured: false,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Adewale Johnson',
  agentContact: '+2348023345569',
  agency: 'Lekki Prime Homes',
  schoolsNearby: ['Lekki British School'],
  transportLinks: ['Bus stop 50m', 'Highway 200m'],
  keywords: ['semi-detached', '3-bedroom', 'rent-to-own', 'pool', 'garden'],
  latitude: 6.4430,
  longitude: 3.5320,
},
{
  id: 37,
  title: '2-Bedroom Apartment, Yaba, Lagos',
  description: 'Affordable apartment for rent-to-own, ideal for small families.',
  propertyType: 'rent-to-own',
  category: 'apartment',
  address: '22 Herbert Macaulay Way, Yaba',
  location: 'Near Yaba Tech',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '100212',
  images: ['/assets/marketplace-assets/rent37.png'],
  bedrooms: 2,
  bathrooms: 2,
  floorSize: 950,
  furnished: true,
  parking: true,
  garden: false,
  pool: false,
  gym: true,
  price: 30000000,
  currency: 'NGN',
  featured: false,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Bola Akinlade',
  agentContact: '+2348028899001',
  agency: 'Yaba Rent2Own Realty',
  schoolsNearby: ['St. Finbarrs College'],
  transportLinks: ['Bus stop 30m', 'Main Road 50m'],
  keywords: ['apartment', '2-bedroom', 'rent-to-own', 'affordable', 'furnished'],
  latitude: 6.5150,
  longitude: 3.3840,
},
{
  id: 38,
  title: '3-Bedroom Townhouse, Lekki Phase 1, Lagos',
  description: 'Well-furnished townhouse with flexible rent-to-own payment.',
  propertyType: 'rent-to-own',
  category: 'townhouse',
  address: '6 Chevron Drive, Lekki Phase 1',
  location: 'Near Chevron Roundabout',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '105102',
  images: ['/assets/marketplace-assets/rent38.png'],
  bedrooms: 3,
  bathrooms: 3,
  floorSize: 1400,
  furnished: true,
  parking: true,
  garden: true,
  pool: true,
  gym: true,
  price: 55000000,
  currency: 'NGN',
  featured: false,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Emeka Okafor',
  agentContact: '+2348035566778',
  agency: 'Lekki Townhouses Ltd',
  schoolsNearby: ['Lekki British School'],
  transportLinks: ['Bus stop 50m', 'Highway 150m'],
  keywords: ['townhouse', '3-bedroom', 'rent-to-own', 'furnished', 'pool'],
  latitude: 6.4440,
  longitude: 3.5330,
},
{
  id: 39,
  title: '4-Bedroom Duplex, Ikoyi, Lagos',
  description: 'Spacious duplex available for rent-to-own buyers seeking luxury.',
  propertyType: 'rent-to-own',
  category: 'duplex',
  address: '14 Bourdillon Road, Ikoyi',
  location: 'Near Ikoyi Club',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '101233',
  images: ['/assets/marketplace-assets/rent39.png'],
  bedrooms: 4,
  bathrooms: 4,
  floorSize: 2600,
  furnished: true,
  parking: true,
  garden: true,
  pool: true,
  gym: true,
  price: 140000000,
  currency: 'NGN',
  featured: true,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Funke Adeyemi',
  agentContact: '+2348033345566',
  agency: 'Ikoyi Prime Estates',
  schoolsNearby: ['Corona Ikoyi'],
  transportLinks: ['Bus stop 60m', 'Main Road 80m'],
  keywords: ['duplex', '4-bedroom', 'rent-to-own', 'luxury', 'pool'],
  latitude: 6.4285,
  longitude: 3.4290,
},
{
  id: 40,
  title: '3-Bedroom Semi-Detached House, Lekki, Lagos',
  description: 'Comfortable semi-detached house with rent-to-own option.',
  propertyType: 'rent-to-own',
  category: 'semi-detached',
  address: '10 Admiralty Way, Lekki Phase 1',
  location: 'Near Lekki Toll Gate',
  city: 'Lagos',
  state: 'Lagos',
  postcode: '105102',
  images: ['/assets/marketplace-assets/rent40.png'],
  bedrooms: 3,
  bathrooms: 3,
  floorSize: 1500,
  furnished: true,
  parking: true,
  garden: true,
  pool: true,
  gym: true,
  price: 60000000,
  currency: 'NGN',
  featured: false,
  verified: true,
  isNew: true,
  status: 'available',
  agentName: 'Adewale Johnson',
  agentContact: '+2348023345569',
  agency: 'Lekki Rent2Own Homes',
  schoolsNearby: ['Lekki British School'],
  transportLinks: ['Bus stop 50m', 'Highway 200m'],
  keywords: ['semi-detached', '3-bedroom', 'rent-to-own', 'pool', 'garden'],
  latitude: 6.4435,
  longitude: 3.5340,
},
];


